version: '3'

services:
  api_server:  
    build:
      context: .
    ports:
      - 5000:5000
    restart: always  # Set restart policy to always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
